repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0  # Use the latest version available
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-json
    - id: detect-private-key
    # - id: no-commit-to-branch
    #   args: [--branch, master, --branch, main]


- repo: https://github.com/pycqa/flake8
  rev: 7.1.0  # Use the latest version available
  hooks:
    - id: flake8

- repo: https://github.com/psf/black
  rev: 24.4.2  # Use the latest version available
  hooks:
    - id: black
      args: [--line-length=120]  # Customize line length if needed
